"""empty message

Revision ID: 833a70a79779
Revises: 4ebcb7760e92
Create Date: 2022-04-30 15:21:25.776613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833a70a79779'
down_revision = '4ebcb7760e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
